import type { Metadata } from "next";
import "./globals.css";
import { Logo } from "@/components/logo";
import { Footer } from "@/components/footer/footer";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width" />
        <title>MongolArt</title>
        <link href="https://fonts.googleapis.com/css2?family=DM+Sans:ital,wght@0,400;0,700;1,400;1,700&display=swap" rel="stylesheet" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300..800;1,300..800&family=Oswald:wght@200..700&display=swap" rel="stylesheet" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Jaini&family=Open+Sans:ital,wght@0,300..800;1,300..800&family=Oswald:wght@200..700&display=swap" rel="stylesheet" />
      </head>

      <body style={{ backgroundColor: 'black', display: 'flex', justifyContent: 'center', fontFamily: '"Open Sans", sans-serif' }}>
        <div style={{ width: '1366px' }}>
          <div
            style={{ display: 'flex', flexDirection: 'row', flexGrow: 1, justifyContent: 'space-between', alignItems: 'center', marginTop: '30px', marginBottom: '30px' }}
          >
            {/* Logo */}
            <Logo />

            {/* Search bar */}
            <div>
              <input type="text" placeholder="Хайх" style={{ width: '326px', height: '40px', background: 'white', borderRadius: '90px', border: 'none' }} />
              <button>
                <img style={{ width: '25px', height: '25px' }} src="image/search.png" />
              </button>
            </div>

            {/* Buttons */}
            <div style={{ display: 'flex', flexDirection: 'row', gap: '12px' }}>
              <a href="/user">
                <img style={{ width: '25px', height: '25px' }} src="/image/user.png" />
              </a>
              <a href="/settings">
                <img style={{ width: '25px', height: '25px' }} src="/image/settings.png" />
              </a>
              <a href="/menu">
                <img style={{ width: '30px', height: '30px' }} src="/image/menu.png" />
              </a>
            </div>
          </div>
          <main>
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
